server:
  port: 8082

#国安测试库
guoan_test:
  url: jdbc:mysql://123.59.84.66:3306/guoan_new?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
  driverClass: com.mysql.jdbc.Driver
  user: guoan
  password: rr7ZKIqHsdfje$9h
#泰达测试库
td_test:
  url: jdbc:mysql://120.132.61.35:3306/tianjinfc?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
  driverClass: com.mysql.jdbc.Driver
  user: tjuser
  password: GbqTq9Vzdfj#9h
#申花测试库
sh_test:
  url: jdbc:mysql://123.59.138.131:3306/shanghaifc?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
  driverClass: com.mysql.jdbc.Driver
  user: shuser
  password: j4R71LmKjf#9h

mybatis:
  typeAliasesPackage: com.ninehcom
  mapperLocations: classpath:/sqlmapper/*.xml
  configLocation: classpath:/mybatis-config.xml